version: '3'

services:
  server:
#    restart: unless-stopped
    image: minecraft-ftb-inferno
    container_name: minecraft-ftb-inferno-server
    ports:
      - "35565:25565"
      - "25575:25575"
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./tmp/world
        target: /home/minecraft/world
        read_only: false
      - type: bind
        source: ./tmp/backups
        target: /home/minecraft/backups
        read_only: false
      - type: bind
        source: ./tmp/logs
        target: /home/minecraft/logs
        read_only: false
# the following makes the container's server.properties visible to the host but not the other way round.
#      - type: bind
#        source: ./conf/server.properties
#        target: /home/minecraft/server.properties
#        read_only: true

